name: Nakdan pro tests chrome

on: 
  #push
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6,14,22 * * *'


jobs:
  cypress-e2e:
    name: Run on Chrome 89
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001

    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true


    - name: Install a project with a clean slate
      run: |
        npx ci
        $(npm bin)/cypress cache path
        $(npm bin)/cypress cache list
        $(npm bin)/cypress verify

    - name: Run chrome tests
      run: npx cypress run --browser chrome --spec ./cypress/integration/basicTests.js

    #- name: Run chrome requests tests
      #run: npx cypress run --browser chrome --spec ./cypress/integration/requestsTests.js
      #if: ${{ always() }}

    - name: Copy test execution videos
      run: |
        mkdir public
        cp -r cypress/videos public/videos
      if: ${{ always() }}

    - name: Merge test results into one
      run: npm run report:merge
      if: ${{ always() }}

    - name: Generate HTML report
      run: npm run report:generate
      if: ${{ always() }}

    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      if: ${{ always() }}
